// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoadDW.Data.Entities.DW;

[Table("FactCustomersServedByEmployees", Schema="dbo")]
public partial class FactCustomersServedByEmployee
{
    [Key]
    public int CustomersServedByEmployeeId { get; set; }

    public int? EmployeeKey { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? TotalClients { get; set; }
}