// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDW.Models.Models;

public partial class CustomersServedByEmployee
{
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? TotalCustomers { get; set; }
}