// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDW.Models.Models;

public partial class FactCustomersServedByEmployee
{
    public int CustomersServedByEmployeeId { get; set; }

    public int? EmployeeKey { get; set; }

    public int? TotalClients { get; set; }
}